-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME 
FROM ANIMAL_OUTS O left join ANIMAL_INS I on I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID is null
ORDER BY O.ANIMAL_ID



# SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS O
# LEFT JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID