with recursive TIME
as (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
    )

SELECT T.HOUR as HOUR, count(ANIMAL_ID) as COUNT FROM TIME T
LEFT OUTER JOIN (SELECT *, HOUR(DATETIME) HOUR FROM ANIMAL_OUTS) O on T.HOUR = O.HOUR
GROUP BY HOUR
