-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, 
(SELECT SUM(PRICE) FROM USED_GOODS_BOARD 
 WHERE STATUS = 'DONE' and WRITER_ID = USER_ID) as TOTAL_SALES FROM USED_GOODS_BOARD 
JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# SELECT WRITER_ID, SUM(PRICE) FROM USED_GOODS_BOARD 
# WHERE STATUS = 'DONE' 
# GROUP BY WRITER_ID