-- 코드를 입력하세요
SELECT B.CATEGORY, sum(S.SALES) as TOTAL_SALES from BOOK B
JOIN BOOK_SALES S using (BOOK_ID)
WHERE date_format(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
